version: '3.8'

services:
  agent:
    build:
      target: development
    volumes:
      # Mount source code for hot-reloading
      - ./src:/app/src
      - ./main.py:/app/main.py
      # Mount logs for easy access
      - ./logs:/app/logs
      # Mount data directory
      - ./data:/app/data
    ports:
      - "8000:8000"  # Expose for local development
      - "5678:5678"  # Debug port (e.g., for debugpy)
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - PYTHONDONTWRITEBYTECODE=1
    # Override command for development (e.g., with auto-reload)
    # command: python -m debugpy --listen 0.0.0.0:5678 main.py
    # Or for frameworks like FastAPI:
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: "no"  # Don't auto-restart in dev mode

  qdrant:
    ports:
      - "6333:6333"  # Expose locally for debugging
      - "6334:6334"
    restart: "no"  # Don't auto-restart in dev mode
