[project]
name = "advies-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.0.1",
    "langchain-qdrant>=1.1.0",
    "qdrant-client>=1.15.1",
]
