# Generated by Django 6.0.1 on 2026-02-27 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0009_increase_field_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviesAanvraagEngels',
            fields=[
                ('aanvraag_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_result_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('form_id', models.CharField(default='engels-1', max_length=50)),
                ('ingediend_op', models.DateTimeField(blank=True, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_campaign', models.CharField(blank=True, max_length=500, null=True)),
                ('aangemaakt_op', models.DateTimeField(default=django.utils.timezone.now)),
                ('advies_voor_mezelf', models.CharField(blank=True, max_length=255, null=True)),
                ('aanhef', models.CharField(blank=True, max_length=50, null=True)),
                ('voorletters_roepnaam', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('achternaam', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('geboortedatum', models.DateField(blank=True, null=True)),
                ('land_nationaliteit', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('telefoonnummer', models.CharField(blank=True, max_length=100, null=True)),
                ('vaste_woonplaats', models.CharField(blank=True, max_length=500, null=True)),
                ('meerdere_verzekerden', models.TextField(blank=True, null=True)),
                ('bestemming_land', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('verwachte_duur_verblijf', models.CharField(blank=True, max_length=255, null=True)),
                ('vertrekdatum', models.DateField(blank=True, db_index=True, null=True)),
                ('vertrek_wanneer', models.DateField(blank=True, null=True)),
                ('verwachte_vertrekdatum', models.DateField(blank=True, null=True)),
                ('hoofdreden_verblijf', models.CharField(blank=True, max_length=500, null=True)),
                ('werk_omschrijving', models.TextField(blank=True, null=True)),
                ('plannen_omschrijving', models.TextField(blank=True, null=True)),
                ('interesse_aov', models.CharField(blank=True, max_length=255, null=True)),
                ('loondienst_of_zelfstandig', models.CharField(blank=True, max_length=255, null=True)),
                ('bruto_jaarinkomen', models.CharField(blank=True, max_length=255, null=True)),
                ('bruto_salaris_inkomen', models.CharField(blank=True, max_length=255, null=True)),
                ('interesse_zkv', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('zkv_periode', models.CharField(blank=True, max_length=255, null=True)),
                ('zkv_periode_omschrijving_motivatie', models.TextField(blank=True, null=True)),
                ('zkv_periode_omschrijving', models.TextField(blank=True, null=True)),
                ('huidige_verzekeraar', models.CharField(blank=True, max_length=255, null=True)),
                ('voorkeur_verzekeraar', models.CharField(blank=True, max_length=255, null=True)),
                ('medische_bijzonderheden', models.CharField(blank=True, max_length=255, null=True)),
                ('medische_bijzonderheden_toelichting', models.TextField(blank=True, null=True)),
                ('specifieke_wensen_zkv', models.CharField(blank=True, max_length=255, null=True)),
                ('wensen_toelichting', models.TextField(blank=True, null=True)),
                ('dekking_zwangerschap', models.CharField(blank=True, max_length=255, null=True)),
                ('zwangerschap_toelichting', models.TextField(blank=True, null=True)),
                ('andere_verzekeringen_interesse', models.TextField(blank=True, null=True)),
                ('opmerkingen', models.TextField(blank=True, null=True)),
                ('raw_form_data', models.JSONField(blank=True, null=True)),
                ('relatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviesaanvragen_engels', to='comparator_app.relaties')),
            ],
            options={
                'verbose_name_plural': 'Advies Aanvragen (Engels)',
                'db_table': 'adviesaanvragen_engels',
                'indexes': [models.Index(fields=['email', 'ingediend_op'], name='adviesaanvr_email_870420_idx'), models.Index(fields=['bestemming_land', 'vertrekdatum'], name='adviesaanvr_bestemm_d103a0_idx'), models.Index(fields=['interesse_zkv', 'ingediend_op'], name='adviesaanvr_interes_0c7af7_idx')],
            },
        ),
    ]
