# Generated by Django 6.0.1 on 2026-02-27 13:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0011_adviesaanvraagbelgie'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviesAanvraagWoning',
            fields=[
                ('aanvraag_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_result_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('form_id', models.CharField(default='woning-1', max_length=50)),
                ('ingediend_op', models.DateTimeField(blank=True, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_campaign', models.CharField(blank=True, max_length=500, null=True)),
                ('aangemaakt_op', models.DateTimeField(default=django.utils.timezone.now)),
                ('voornaam', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('achternaam', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('geboortedatum', models.DateField(blank=True, null=True)),
                ('geslacht', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('telefoonnummer', models.CharField(blank=True, max_length=100, null=True)),
                ('nationaliteit', models.CharField(blank=True, max_length=255, null=True)),
                ('woonland_buitenland', models.CharField(blank=True, max_length=255, null=True)),
                ('correspondentie_adres_nl', models.CharField(blank=True, max_length=500, null=True)),
                ('vertrekdatum', models.DateField(blank=True, null=True)),
                ('uitgeschreven_brp', models.CharField(blank=True, max_length=255, null=True)),
                ('woning_straat_huisnummer', models.CharField(blank=True, max_length=500, null=True)),
                ('woning_postcode_plaats', models.CharField(blank=True, max_length=255, null=True)),
                ('woning_land', models.CharField(blank=True, max_length=255, null=True)),
                ('woning_gebruik', models.CharField(blank=True, max_length=500, null=True)),
                ('woning_gebruik_extra', models.TextField(blank=True, null=True)),
                ('soort_woning', models.CharField(blank=True, max_length=255, null=True)),
                ('bouwaard', models.CharField(blank=True, max_length=255, null=True)),
                ('dakbedekking', models.CharField(blank=True, max_length=255, null=True)),
                ('bijzonderheden_woning', models.TextField(blank=True, null=True)),
                ('woning_extra_info', models.TextField(blank=True, null=True)),
                ('interesse_verzekeringen', models.TextField(blank=True, null=True)),
                ('gewenste_startdatum', models.CharField(blank=True, max_length=255, null=True)),
                ('interesse_internationale_verzekeringen', models.TextField(blank=True, null=True)),
                ('opmerkingen', models.TextField(blank=True, null=True)),
                ('raw_form_data', models.JSONField(blank=True, null=True)),
                ('relatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviesaanvragen_woning', to='comparator_app.relaties')),
            ],
            options={
                'verbose_name_plural': 'Advies Aanvragen (Woning)',
                'db_table': 'adviesaanvragen_woning',
                'indexes': [models.Index(fields=['email', 'ingediend_op'], name='adviesaanvr_email_905163_idx')],
            },
        ),
    ]
