# Generated by Django 6.0.1 on 2026-02-27 15:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0012_adviesaanvraagwoning'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferteArbeidsOngeschiktheid',
            fields=[
                ('aanvraag_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_result_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('form_id', models.CharField(default='ao-1', max_length=50)),
                ('ingediend_op', models.DateTimeField(blank=True, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_campaign', models.CharField(blank=True, max_length=500, null=True)),
                ('aangemaakt_op', models.DateTimeField(default=django.utils.timezone.now)),
                ('geslacht', models.CharField(blank=True, max_length=50, null=True)),
                ('achternaam', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('voorletters', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('geboortedatum', models.DateField(blank=True, null=True)),
                ('telefoonnummer', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('nationaliteit', models.CharField(blank=True, max_length=255, null=True)),
                ('bestemming_land', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('vertrekdatum', models.DateField(blank=True, db_index=True, null=True)),
                ('vertrek_wanneer', models.DateField(blank=True, null=True)),
                ('verwachte_vertrekdatum', models.DateField(blank=True, null=True)),
                ('verwachte_duur_verblijf', models.CharField(blank=True, max_length=255, null=True)),
                ('bruto_jaarinkomen', models.CharField(blank=True, max_length=255, null=True)),
                ('jaarrente_verzekerd_bedrag', models.CharField(blank=True, max_length=255, null=True)),
                ('werk_omschrijving', models.TextField(blank=True, null=True)),
                ('werkzaamheden', models.CharField(blank=True, max_length=500, null=True)),
                ('salaris_uit_nederland', models.CharField(blank=True, max_length=255, null=True)),
                ('loondienst_of_zelfstandig', models.CharField(blank=True, max_length=255, null=True)),
                ('eigen_onderneming_3jaar', models.CharField(blank=True, max_length=255, null=True)),
                ('loon_doorbetaald_bij_ziekte', models.CharField(blank=True, max_length=500, null=True)),
                ('toelichting_uitkering', models.TextField(blank=True, null=True)),
                ('bouwplaats_of_offshore', models.CharField(blank=True, max_length=255, null=True)),
                ('bouwplaats_hoe_vaak', models.CharField(blank=True, max_length=255, null=True)),
                ('reist_veel_voor_werk', models.CharField(blank=True, max_length=255, null=True)),
                ('frequentie_vervoersmiddel', models.TextField(blank=True, null=True)),
                ('gevaarlijke_stoffen', models.CharField(blank=True, max_length=255, null=True)),
                ('toelichting_gevaarlijke_stoffen', models.TextField(blank=True, null=True)),
                ('interesse_zkv', models.CharField(blank=True, max_length=255, null=True)),
                ('ziektekosten', models.CharField(blank=True, max_length=255, null=True)),
                ('huidige_verzekeraar_ziektekosten', models.CharField(blank=True, max_length=255, null=True)),
                ('interesse_levensverzekering', models.CharField(blank=True, max_length=255, null=True)),
                ('levensverzekering', models.CharField(blank=True, max_length=255, null=True)),
                ('rookt', models.CharField(blank=True, max_length=255, null=True)),
                ('gewenste_verzekerde_som', models.CharField(blank=True, max_length=255, null=True)),
                ('opmerkingen', models.TextField(blank=True, null=True)),
                ('hoe_gevonden', models.CharField(blank=True, max_length=255, null=True)),
                ('opmerkingen_2', models.TextField(blank=True, null=True)),
                ('raw_form_data', models.JSONField(blank=True, null=True)),
                ('relatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offertes_ao', to='comparator_app.relaties')),
            ],
            options={
                'verbose_name_plural': 'Offertes Arbeidsongeschiktheid',
                'db_table': 'offertes_arbeidsongeschiktheid',
                'indexes': [models.Index(fields=['email', 'ingediend_op'], name='offertes_ar_email_ee0446_idx'), models.Index(fields=['bestemming_land', 'vertrekdatum'], name='offertes_ar_bestemm_8ac4b9_idx')],
            },
        ),
    ]
