# Generated by Django 6.0.1 on 2026-02-27 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0013_offertearbeidsongeschiktheid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianzCareQuote',
            fields=[
                ('aanvraag_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_result_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('form_id', models.CharField(default='allianz-1', max_length=50)),
                ('ingediend_op', models.DateTimeField(blank=True, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_campaign', models.CharField(blank=True, max_length=500, null=True)),
                ('aangemaakt_op', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('geboortedatum', models.DateField(blank=True, null=True)),
                ('nationaliteit', models.CharField(blank=True, max_length=255, null=True)),
                ('family_members', models.TextField(blank=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('current_country', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('purpose_of_stay', models.CharField(blank=True, max_length=500, null=True)),
                ('expected_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('area_of_cover', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('cover_inpatient', models.CharField(blank=True, max_length=255, null=True)),
                ('deductible_inpatient', models.CharField(blank=True, max_length=255, null=True)),
                ('deductible_outpatient', models.CharField(blank=True, max_length=255, null=True)),
                ('opmerkingen', models.TextField(blank=True, null=True)),
                ('raw_form_data', models.JSONField(blank=True, null=True)),
                ('relatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allianz_care_quotes', to='comparator_app.relaties')),
            ],
            options={
                'verbose_name_plural': 'Allianz Care Quotes',
                'db_table': 'allianz_care_quotes',
                'indexes': [models.Index(fields=['email', 'ingediend_op'], name='allianz_car_email_ed800d_idx'), models.Index(fields=['destination', 'start_date'], name='allianz_car_destina_76d167_idx')],
            },
        ),
    ]
